[Icon Theme]
Name=sioul-dark
Comment=The Breeze icons Sioul uses (LGPL-3.0-or-later)
Directories=actions/16,actions/22,actions/32,applets/22,applets/48,apps/48,devices/16,devices/22,emblems/16,emblems/22,mimetypes/16,mimetypes/22,mimetypes/32,places/16,places/22,places/32,status/16,status/22

[actions/16]
Size=16
Type=Fixed

[actions/22]
Size=22
Type=Fixed

[actions/32]
Size=32
Type=Fixed

[applets/22]
Size=22
Type=Fixed

[applets/48]
Size=48
Type=Fixed

[apps/48]
Size=48
Type=Fixed

[devices/16]
Size=16
Type=Fixed

[devices/22]
Size=22
Type=Fixed

[emblems/16]
Size=16
Type=Fixed

[emblems/22]
Size=22
Type=Fixed

[mimetypes/16]
Size=16
Type=Fixed

[mimetypes/22]
Size=22
Type=Fixed

[mimetypes/32]
Size=32
Type=Fixed

[places/16]
Size=16
Type=Fixed

[places/22]
Size=22
Type=Fixed

[places/32]
Size=32
Type=Fixed

[status/16]
Size=16
Type=Fixed

[status/22]
Size=22
Type=Fixed
